# Define all components for the deployment
# Different subgroups are created to help the deployment process
# No need to modify
[all:children]
helper
bootstrap
masters
workers
infra

[masters:children]
master0
master1
master2

[workers:children]
worker0
worker1
worker2

[infra:children]
infra0
infra1
infra2

[master0]
master-0

[master1]
master-1

[master2]
master-2

[worker0]
compute-0

[worker1]
compute-1

[worker2]
compute-2

[infra0]
infra-0

[infra1]
infra-1

[infra2]
infra-2

# Variables which apply for all components
# First vSphere related settings, go through carefully and modify correct settings
[all:vars]

# OCP version which is used to download proper clients from Red Hat
ocp_version= 4.1.4

# Instance network information, used for DHCP configuration
mgmt_gw= 192.168.1.1
bootstrap_gw = 192.168.1.1
masters_gw = 192.168.1.1
workers_gw = 192.168.1.1
infra_gw = 192.168.1.1
mgmt_nm= 255.255.255.0
masters_nm= 255.255.255.0
workers_nm= 255.255.255.0
infra_nm= 255.255.255.0
bootstrap_nm = 255.255.255.0
# External DNS which is given as a default to each node with DHCP
ext_dns= ["172.28.11.111", "172.28.11.112"]
ntp_server= 192.168.100.100

# HTTP Proxy setting for downloading the installation packages to helper node
# Environment name and base domain definitions
env_name= ocp
base_domain= example.com
domain= "{{ env_name }}.{{ base_domain }}"

# Subscription information for OCP installer
pull_secret= '{ auth ... }'

# Node type specific settings, use this section to define how much resources is allocated
# Note: disk_size should be the same as defined for the template, default of 120GB is currently used

[masters:vars]
cpu= 4
ram_mb= "16384"
disk_size= "120"
vmware_network_name= "ocp_network_vlan"

[workers:vars]
cpu= 4
ram_mb= "16384"
disk_size= "120"
vmware_network_name= "ocp_network_vlan"

[infra:vars]
cpu= 4
ram_mb= "16384"
disk_size= "120"
vmware_network_name= "ocp_network_vlan"

# Bootstrap is only one node, so node + host specific settings are in one place
[bootstrap:vars]
name= bootstrap
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}
ip= 192.168.1.10
cpu= 4
ram_mb= "16384"
disk_size= "120"

# Host specific variables, IP should be the only one changed
[master0:vars]
name= master-0
ip= 192.168.1.11
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[master1:vars]
name= master-1
ip= 192.168.1.12
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[master2:vars]
name= master-2
ip= 192.168.1.13
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[worker0:vars]
name= compute-0
ip= 192.168.1.20
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[worker1:vars]
name= compute-1
ip= 192.168.1.21
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[worker2:vars]
name= compute-2
ip= 192.168.1.22
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[infra1:vars]
name= infra-0
ip= 192.168.1.23
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[infra2:vars]
name= infra-1
ip= 192.168.1.24
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}

[infra3:vars]
name= infra-2
ip= 192.168.1.25
fqdn= {{ name }}.{{ env_name }}.{{ base_domain }}
